env:
 - CABALVER=1.22 GHCVER=7.8.4
 - CABALVER=1.22 GHCVER=7.10.1
 - CABALVER=head GHCVER=head

matrix:
  allow_failures:
    - env: CABALVER=head GHCVER=head

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - cabal update

  - travis_retry sudo apt-get install alex-3.1.3
  - export PATH=/opt/alex/3.1.3/bin:$PATH

  - cabal install --only-dependencies --enable-tests

install:
  - cabal configure --enable-tests --enable-library-coverage
  - cabal build

script:
  - cabal test

after_script:
 - cabal install hpc-coveralls
 - hpc-coveralls tests

notifications:
  email:
    recipients: omeragacan@gmail.com
    on_success: change
    on_failure: change
